var I18N = {
	// 详细信息页面右侧功能按钮下拉菜单国际化
	rediscovery : "重新发现",
	modifydispname : "修改显示名称",
	offlinetime : "设置计划不在线",
	maintaininfo : "设置维护信息",
	modifyremark : "修改备注",
	addgroup : "加入资源组",
	deleteRes : "删除",
  monitor : "个性化监控",
  strategy : "选择策略",
  refresh : "刷新设备",
  changetype : "变更设备类型",
  changefindinfo : "变更发现信息",
  diagnose : "诊断",
  detail_availstatistics : "可用性统计",
  detail_refreshequip_successmsg : "刷新设备成功。",
  detail_topolocation_msg : "此资源不在拓扑中。",
  detail_nobottomequip_msg : "没有下联设备",
  detail_relanonservice_msg : "当前资源未关联任何业务服务。",
  detail_relaservice_info : "关联服务信息",
  detail_operator_successmsg : "操作成功。",
  detail_msg_resnonexistordelete : "该资源实例不存在或已删除。",
  detail_msg_resnonmonitor : "该资源实例未监控。",
  detail_msg_resnonpermission : "没有访问该资源的权限。",
  // 资源状态
  "lamp lamp-gray" : "当前资源可用性未知。",
  "lamp lamp-green" : "当前资源可用。",
  "lamp lamp-greenblack" : "1.当前资源可用；2.资源或其组件有配置变更。",
  "lampshine-blackbg-ico lampshine-blackbg-ico-greenred" : "1.当前资源可用；2.资源或其组件的性能出现问题，一个或多个性能指标违反红色阈值，或某些组件不可用；3.无配置变更。",
  "lampshine-ico lampshine-ico-greenred" : "1.当前资源可用；2.资源或其组件的性能出现问题，一个或多个性能指标违反红色阈值，或某些组件不可用；3.无配置变更。",
  "lampshine-blackbg-ico lampshine-blackbg-ico-alert-greenred" : "1.当前资源可用；2.资源或其组件的性能出现问题，一个或多个性能指标违反红色阈值，或某些组件不可用；3.资源或其组件有配置变更。",
  "lampshine-ico lampshine-ico-alert-greenred" : "1.当前资源可用；2.资源或其组件的性能出现问题，一个或多个性能指标违反红色阈值，或某些组件不可用；3.资源或其组件有配置变更。",
  "lampshine-blackbg-ico lampshine-blackbg-ico-greenyellow" : "1.当前资源可用；2.资源或其组件的性能出现问题，一个或多个性能指标违反黄色阈值；3.无配置变更。",
  "lampshine-ico lampshine-ico-greenyellow" : "1.当前资源可用；2.资源或其组件的性能出现问题，一个或多个性能指标违反黄色阈值；3.无配置变更。",
  "lampshine-blackbg-ico lampshine-blackbg-ico-alert-greenyellow" : "1.当前资源可用；2.资源或其组件的性能出现问题，一个或多个性能指标违反黄色阈值；3.资源或其组件配置变更。",
  "lampshine-ico lampshine-ico-alert-greenyellow" : "1.当前资源可用；2.资源或其组件的性能出现问题，一个或多个性能指标违反黄色阈值；3.资源或其组件配置变更。",
  "lampshine-blackbg-ico lampshine-blackbg-ico-greengray" : "1.当前资源可用；2.资源或其组件的性能出现问题，一个或多个性能指标未知；3.无配置变更。",
  "lampshine-ico lampshine-ico-greengray" : "1.当前资源可用；2.资源或其组件的性能出现问题，一个或多个性能指标未知；3.无配置变更。",
  "lampshine-blackbg-ico lampshine-blackbg-ico-alert-greengray" : "1.当前资源可用；2.资源或其组件的性能出现问题，一个或多个性能指标未知；3.资源或其组件配置变更。",
  "lampshine-ico lampshine-ico-alert-greengray" : "1.当前资源可用；2.资源或其组件的性能出现问题，一个或多个性能指标未知；3.资源或其组件配置变更。",
  "lamp lamp-red" : "当前资源不可用。"
};
